### ISSUE TITLE
AMQP reached 1.0.0

### ISSUE THREAD

**Issue by philipgiuliani** [StoiximanServices/exrabbitmq#5]
AMQP reached 1.0.0 a few days ago! Would be nice to see the library updated. Thanks a lot for your effort! :)

https://github.com/pma/amqp

**Comment by indyone** [comment]
Indeed... we are planing to upgrade to AMQO 1.x along with the support of Elixir 1.6.
We are working on a new branch `elixir-1.6` where we doing or tests, and eventually merge it back to `master`

**Comment by brunoripa** [comment]
Is this still work in progress ?

**Comment by indyone** [comment]
Hallo @brunoripa 
Yes, this is still in progress. There is this branch [multiple_declarations](https://github.com/StoiximanServices/exrabbitmq/blob/multiple_declarations) where we are using `pma/amqp` v1.1
Please note that this branch contains breaking changes with the current stable version on master.

**Comment by brunoripa** [comment]
Hi @indyone ,

   very good news! I am working on a project and i am using ExRabbitMQ (which has AMQP has a dependency), so i will have eyes on this !

Keep up the good work !

**Comment by dennisxtria** [comment]
Hello @brunoripa,

AMQP has been updated to the latest version along the rest of the deps, so please update accordingly.

Thank you!

**Comment by brunoripa** [comment]
Hi @dennisxtria,

that's good news ! I have already communicated we'll review and update the deps ;-)

Thanks a lot !
